### PR TITLE
Remove 'create a personal OAuth2 token' as link

### PR DESCRIPTION
**Pull request by SriMethan**
since in lidraughts these link don't works

### CODE REVIEW

**Comment by AttackingOrDefending** [comment]
I think that I should leave the link, because it provides direct access to the token creation page. If I merge this, then they would have to go to lidraughts, go to settings etc., while it is easier with the link.

**Comment by SriMethan** [comment]
@AttackingOrDefending Okay I kept that link but not with scopes[]=bot:play&description=lidraughts-bot

**Comment by AttackingOrDefending** [comment]
Can you also remove the "?" from the link?

**Comment by SriMethan** [comment]
@AttackingOrDefending Removed

**Pull request merged**
