### PR TITLE
Make sure that the .gitignore file is empty

### PR DESCRIPTION
**Pull request by lidevelopers**

### CODE REVIEW

**Comment by TheYoBots** [comment]
Why on Earth would you want to hide make sure the gitignore is empty. That makes no sense at all.

**Comment by AttackingOrDefending** [comment]
It makes sense because this is the guide for heroku. Otherwise your config.yml won't be uploaded.
I think 'Delete .gitignore' would be better.

**Comment by TheYoBots** [comment]
But locally the gitignore file doesn’t matter.

**Comment by AttackingOrDefending** [comment]
Heroku git won't upload a file if it is mentioned in the .gitignore, so we have to delete it.

**Comment by TheYoBots** [comment]
That is a fair enough statement, but the `.gitignore` file is a bit weird so to say. So generally when adding a file to the `.gitignore` you’d expect that the gitignor’d would be deleted along with that commit, but that’s not the case. The `.gitignore` file just prevents your from creating a new config.yml file, so simply renaming the file in the `.` directory doesn’t delete the file. Probably a GitHub bug, but since that’s how it works it isn’t needed, but if you’d like it then you could go ahead. It’s after all up to you.

**Comment by AttackingOrDefending** [comment]
The .gitignore file also prevents the engine from being uploaded, because it only allows the README.md to be uploaded from the engines folder.

**Pull request closed without merging**
